Repository openMVG/openMVG, pull requests merged in 2022-04, with the labels that each got.

#2038 builds on Mac OS 12 AppleClang + OpenMP
  src/CMakeLists.txt
Labels: build

#2049 Pull Request cxx20
  src/openMVG/cameras/Camera_Intrinsics.hpp
  src/openMVG/features/sift/octaver.hpp
  src/openMVG/system/loggerprogress.hpp
  src/openMVG/system/progressinterface.hpp
  src/third_party/lemon/lemon/bits/array_map.h
Labels: enhancement, build

#2055 software: store relative paths in MVS scene
  src/software/SfM/export/main_openMVG2openMVS.cpp
Labels: enhancement
